<section>
	<div class="row">
		<div class="box">
	    	<hr>
			<h1>Gestion des blagues</h1>
			<hr>
			<?php if(!empty($_SESSION["successLoginMessage"])) : ?>
			<div class="alert alert-success" role="alert"><?= ucfirst($_SESSION['username']) . $_SESSION["successLoginMessage"]; ?></div>
			<?php unset($_SESSION['successLoginMessage']); ?> 
			<?php endif; ?>
			<?php if(!empty($_SESSION["successAddJokeMessage"])) : ?>
			<div class="alert alert-success" role="alert"><?= $_SESSION["successAddJokeMessage"]; ?></div>
			<?php unset($_SESSION['successAddJokeMessage']); ?> 
			<?php endif; ?>
			<?php if(!empty($_SESSION["successEditJokeMessage"])) : ?>
			<div class="alert alert-success" role="alert"><?= $_SESSION["successEditJokeMessage"]; ?></div>
			<?php unset($_SESSION["successEditJokeMessage"]); ?> 
			<?php endif; ?>
			<?php if(!empty($_SESSION["successDeleteJokeMessage"])) : ?>
			<div class="alert alert-success" role="alert"><?= $_SESSION['successDeleteJokeMessage']; ?></div>
			<?php unset($_SESSION["successDeleteJokeMessage"]); ?> 
			<?php endif; ?>
	    	<div class="col-lg-12">
		    	<div class="row">
		    		<div class="col-md-offset-3 col-md-6 text-center">
						<a href="add-joke" id="add-joke-btn" class="btn btn-primary" role="button">Ajouter une blague/citation !</a>
					</div>
				</div>
				<div class="table-responsive">
					<table class="table">
						<caption>Liste des blagues et citations</caption>
						<thead>
							<tr>
								<th>Joke ID</th>
								<th>Contenu</th>
								<th>Public</th>
								<th>Type</th>
								<th>Créé le</th>
								<th>Entré par</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($jokes as $value) : ?>
								<tr>
									<td><?= $value["joke_ID"] ?></a></td>
									<td class="is-breakable"><?= mb_strimwidth($value["joke_content"], 0, 100, "[...]") ?></td>
									<td><?= $value["joke_audience"] ?></td>
									<td><?= $value["joke_tagType"] ?></td>
									<td><?= $value["joke_dateCreation"] ?></td>
									<td><?= $value["user_username"] ?></td>
									<td>
										<a href="edit-joke?joke_ID=<?= $value["joke_ID"] ?>" class="btn btn-info center-block" role="button">Éditer</a>
										<a href="delete-joke?joke_ID=<?= $value["joke_ID"] ?>" class="btn btn-danger center-block" role="button" data-toggle="confirmation">Supprimer</a>
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
				<!-- /.table-responsive -->
			</div>
			<!-- /.col-lg-12 -->
		</div>
		<!-- /.box -->
	</div>
	<!-- /.row -->
</section>
