<section>
  <div class="row">
    <div class="box">
      <hr>
      <h1>Connexion</h1>
      <hr>
      <div class="col-lg-12">
        <form id="login-form" class="form-horizontal col-md-offset-2 col-md-8"  method="POST" action="login">
          <?php if(!empty($errorLoginMessage)) : ?>
          <div class="alert alert-danger" role="alert"><?= $errorLoginMessage ?></div>
          <?php endif; ?>
          <div class="form-group">
            <label class="col-md-3 col-md-offset-2 control-label" for="username">Nom d'utilisateur</label>
            <div class="col-md-5">
              <div class="input-group"><span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                <input id="username" name="username" type="text" class="form-control input-md" required>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-3 col-md-offset-2 control-label" for="password">Mot de passe</label>
            <div class="col-md-5">
              <div class="input-group"><span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
                <input id="password" name="password" type="password" class="form-control input-md" required>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-4 col-md-offset-1 control-label" for="Submit"></label>
            <div class="col-md-4">
              <button id="Submit" class="btn btn-success" type="Submit">Valider</button>
            </div>
          </div>
        </form>
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.box -->
  </div>
  <!-- /.row -->
</section>