<section>
	<div class="row">
	    <div class="box">
	        <div class="col-lg-12">
	            <hr>
	            <h1>The story</h1>
	            <hr>
	            <div class="row">
	                <div class="col-lg-12">
	                    <div id="share-bar" class="text-center"></div>
	                </div>
            	</div>
            	<figure class="figure-left">
	            	<img class="img-responsive img-border" src="img/jean-et-manu-3wa.jpg" alt="Jean et Manu de la session LY15 - 3W Academy Lyon">
	            	<figcaption>Jean (au premier plan) et Manu</figcaption>
	            </figure>
	            <h2>Jean Lorem, c’est quoi ?</h2>
				<p>Jean Lorem est un <a href="/">générateur</a> de texte aléatoire comparable au <a href="https://fr.wikipedia.org/wiki/Faux-texte">Lorem Ipsum</a>.</p>
				<p>Sa particularité est d'utiliser les blagues et citations préférées de Jean, étudiant plus tout jeune (mais respectable) de la session n°15 de la <a href="https://3wa.fr/">3W Academy</a> à Lyon.</p> 
				<p>Jean s’est notamment fait remarquer par sa persévérance mais également par l’emploi d’un langage très particulier, rarement vu dans le monde du développement web : le langage fleuri.</p>

				<h2>Jean Lorem, pour qui ?</h2>
				<p>Tout comme le Lorem Ipsum, Jean Lorem est avant tout destiné aux professionnels de l’édition, du graphisme, de l’intégration ou du développement web et plus généralement à tous ceux qui ont besoin de "faux-texte" afin de mettre en forme des maquettes (avant d'insérer le vrai contenu).</p>
				<p>Mais Jean Lorem peut être utilisé par tous !</p>
				<p>La différence principale de Jean Lorem, comparativement au Lorem Ipsum, est que son contenu peut attirer l’oeil !</p>
				<p>Aussi, il est à noter que Jean Lorem utilise des caractères accentués.</p>

				<h2>Jean Lorem, pourquoi ?</h2>
				<p>Pour générer du Lorem Ipsum original !</p>
				<p>Pour se remémorer, faire perdurer et faire connaître au plus grand nombre les sorties (pas toujours très fines, nous l'avouons) de Jean !</p>
				<p>Pour moi (Emmanuel Baracand alias Manu), la création de ce site a été un exercice technique qui m'a permis de m'entraîner à travailler avec plusieurs langages de programmation.</p>

				<h2>Jean Lorem, remerciements :</h2>
				<p>Un grand merci à nos formateurs de la <a href="https://3wa.fr/">3W Academy</a>, Vanessa et Pierre, pour tout ce qu’ils nous ont appris (parfois non sans mal) !</p>
				<p>Et chapeau bas à toute la session LY15, un groupe de personnes issues d’univers totalement différents réunis par la même passion.</p>

				<h2>Jean Lorem, les sources :</h2>
				<p>Nombre des blagues et citations proviennent de la spontanéité de Jean.</p>
				<p>Cependant, Jean n'est pas l’auteur initial de toutes les expressions du générateur. Certaines existent depuis longtemps dans le langage commun et d'autres sont des blagues plus ou moins connues que Jean affectionne.</p>
	        </div>
	    </div>
	</div>
</section>